sotsuken_site/grareco_site/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sign.urls')),
    path('<str:username>/', include('user.urls')),
]

sotsuken_site/reco/urls.py
from django.urls import path
from . import views

app_name = 'reco'

urlpatterns = [
    path('', views.reco, name='reco'),
]

sotsuken_site/show/urls.py
from django.urls import path
from . import views

app_name = 'show'

urlpatterns = [
    path('', views.show, name='show'),
    path('<str:title>/', views.show_contents, name='show_contents'),
]

sotsuken_site/sign/urls.py
from django.urls import path
from . import views

app_name = 'sign'

urlpatterns = [
    path('', views.sign, name='sign'),
    path('in/', views.signin, name='signin'),
    path('out/', views.signout, name='signout'),
]

sotsuken_site/user/urls.py
from django.urls import include, path
from . import views

app_name = 'user'

urlpatterns = [
    path('', views.user, name='user'), 
    path('reco/', include('reco.urls')),
    path('show/', include('show.urls')),
]

sotsuken_site/sign/models.py
from django.db import models

# Create your models here.

sotsuken_site/user/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin
from django.core.validators import MinLengthValidator, RegexValidator

# Create your models here.
class UserManager(BaseUserManager):
    def create_user(self, username, password=None):
        if not username:
            raise ValueError('Users must have an username')

        user = self.model(
            username=username,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, password):
        user = self.create_user(
            username=username,
            password=password,
        )
        user.is_admin=True
        user.is_staff=True
        user.is_superuser=True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(
        verbose_name='username',
        unique=True,
        max_length=20,
        help_text='Required. 20 characters or fewer. Letters, digits and @/./+/-/_ only.',
        validators=[MinLengthValidator(3,), RegexValidator(r'^[a-zA-Z0-9]*$',)],
        error_messages={
            'unique': "A user with that username already exists.",
        },
    )
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)\
       
    objects = UserManager()
    
    USERNAME_FIELD = 'username'
    
    REQUIRED_FIELDS = []
    
    def __str__(self):
        return self.username

sotsuken_site/reco/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def reco(request, username):
    
    sentences = ['I walk', 'around my house', 'all day long.']
    context = {'sentences':sentences}
    
    return render(request, 'reco.html', context)

sotsuken_site/show/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def show(request, username):
    
    titles = ['The breakfast', 'Shooting stars', 'I have many cap of popcorn']
    context = {'titles':titles}
    
    return render(request, 'show.html', context)

@login_required
def show_contents(request, username, title):
    
    #That title already have been generated
    bool_generated = True
    
    Edit_Mode = False
    
    if bool_generated == True:
    
        context = {'title':title}
        
        return render(request, 'show_contents.html', context)
    
    else:
        return redirect('show:show')

sotsuken_site/sign/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from urllib.parse import urlencode
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
def sign(request):
     
    if 'e_code' in request.GET:
        e_code = request.GET.get['e_code']
        e_message=''

        if e_code == '1':
            #no match
            e_message = 'Username and Password don\'t match.'
        elif e_code == '2':
            #account blocked
            e_message = 'This account is blocked.'
        elif e_code == '3':
            ##could not send
            e_message = 'This request couldn\'t send properly. Please try agein.'
        
        return render(request, 'sign.html', {'error' : e_message})      
      
    return render(request, 'sign.html')


@csrf_exempt
def signin(request):
    if request.method == 'POST':
        #if the request is for signin, check username and password
        """if(request.POST.get('User_sign_in', None) == 'user'):
            name = request.POST.get('username')
            pasw = request.POST.get('password')
            user = authenticate(username=name, password=pasw)
            
            return user_certificate(request, user)"""
        if(request.POST.get('Guest_sign_in', None) == 'guest'):
            name = 'guest'
            pasw = 'g1234pass'
            user = authenticate(username=name, password=pasw)

            return signin_certificate(request, user)
    
    #failed
    return signin_failed()


def signin_certificate(request, user):
    if user:
        if user.is_active:
            #succeeded
            login(request,user)
            request.session['username'] = user.username
            return signin_success(request)
        else:
            #account blocked error
            redirect_url = reverse('sign:sign')
            parameters = urlencode({'e_code':'2'})
            return redirect(f'{redirect_url}?{parameters}', permanent=True)
    else:
        #no match error
        redirect_url = reverse('sign:sign')
        parameters = urlencode({'e_code':'1'})
        return redirect(f'{redirect_url}?{parameters}', permanent=True)
  
    
def signin_failed():
        #could not send error
        redirect_url = reverse('sign:sign')
        parameters = urlencode({'e_code':'3'})
        return redirect(f'{redirect_url}?{parameters}', permanent=True)


def signin_success(request):
     url_name = request.session.get('username', None)
     if url_name:
         redirect_url = reverse('user:user', kwargs={'username':url_name})
         return redirect(redirect_url)
     return signin_failed()

@csrf_exempt
def signout(request):
    logout(request)
    return redirect('sign:sign', permanent=True)

sotsuken_site/user/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
@csrf_exempt
@login_required
def user(request, **kwargs):
    return render(request, 'user.html')

sotsuken_site/reco/templates/reco.html
<!DOCTYPE html>
<html lang="jp">

<head></head>

<body>
    <a href="../">メニュー</a>
    <h2>録音</h2>
    <input buttonid="button1" type="button" value="rec" onclick="myfunc(this)">
    <input buttonid="button2" type="button" value="pose" onclick="myfunc(this)">

    {% for sentence in sentences %}
        <p>{{ sentence }}</p>
    {% endfor %}
</body>
<!--
<script>
    var connection = null;
    var myfunc = function (button) {


        if (button.value == "open") {
            var handleSuccess = function (stream) {
                var context = new AudioContext();
                var input = context.createMediaStreamSource(stream)
                var processor = context.createScriptProcessor(1024, 1, 1);


                // WebSocketのコネクション
                connection = new WebSocket('ws://hogehoge.com:8000/websocket');

                input.connect(processor);
                processor.connect(context.destination);

                processor.onaudioprocess = function (e) {
                    var voice = e.inputBuffer.getChannelData(0);

                    connection.send(downsampleBuffer(voice, context.sampleRate, 16000)); // websocketで送る
                };
            };

            navigator.mediaDevices.getUserMedia({ audio: true, video: false })
                .then(handleSuccess)

            var time1 = function () {
                connection.close();
                context.close()
            };

            setTimeout(time1, 1000 * 60 * 3);
        }
        if (button.value == "close") {
            connection.close();
            context.close()
        };
    };

    const downsampleBuffer = (buffer, sampleRate, outSampleRate) => {
        if (outSampleRate > sampleRate) {
            console.error('downsampling rate show be smaller than original sample rate');
        }

        const sampleRateRatio = sampleRate / outSampleRate;
        const newLength = Math.round(buffer.length / sampleRateRatio);
        const result = new Int16Array(newLength);
        let offsetResult = 0;
        let offsetBuffer = 0;
        // bpsを縮める処理 (n byte分のデータを合算して、n byteで割る)
        while (offsetResult < result.length) {
            const nextOffsetBuffer = Math.round((offsetResult + 1) * sampleRateRatio);

            // 次のoffsetまでの合計を保存
            let accum = 0;
            let count = 0;
            for (let i = offsetBuffer; i < nextOffsetBuffer && i < buffer.length; i += 1) {
                accum += buffer[i];
                count += 1;
            }

            // 16進数で保存 (LINEAR16でストリーミングするため)
            result[offsetResult] = Math.min(1, accum / count) * 0x7FFF;
            offsetResult += 1;
            offsetBuffer = nextOffsetBuffer;
        }
        return result.buffer;
    };
</script>
-->

</html>

sotsuken_site/show/templates/show.html
<!DOCTYPE html>
<html lang="jp">

<head></head>

<body>
    <a href="../">メニュー</a>
    <p>閲覧</p>

    {% for title in titles %}
        <p><a href="{{ title }}/">{{ title }}</a></p>
    {% endfor %}
</body>

</html>

sotsuken_site/show/templates/show_contents.html
<!DOCTYPE html>
<html lang="jp">

<head></head>

<body>
    <a href="../">一覧に戻る</a>
    <p>{{ title }}</p>

</body>

</html>

sotsuken_site/sign/templates/sign.html
<!DOCTYPE html>
<html lang="jp">

<head></head>

<body>
    <form action="{% url 'sign:signin' %}" method="POST">
        {% csrf_token %}
        <button type="submit" name="Guest_sign_in" value="guest">Guest SignIn</button>
    </form>
    {% if error %}<p>{{ error }}</p>{% endif %}
</body>

</html>

sotsuken_site/signin/templates/signin.html
<!DOCTYPE html>
<html lang="jp">

<head></head>

<body>
    <form action="{% url 'user:user' %}" method="POST">
        {% csrf_token %}
        <button type="submit" name="Guest_sign_in" value="guest">Guest SignIn</button>
    </form>
    <p>{{ error }}</p>
</body>

</html>

sotsuken_site/user/templates/user.html
<!DOCTYPE html>
<html lang="jp">

<head></head>

<body>
    <p>ログイン：{{ user.username }}</p>
    <h3><a href="/{{ user.username }}/reco/">収録</a></h3>
    <h3><a href="/{{ user.username }}/show/">閲覧</a></h3>
    <form action="{% url 'sign:signout'%}" method="POST">
        {% csrf_token %}
        <button type="submit" name="sign_out" value="signout">SignOut</button>
    </form>
</body>

</html>